"""Core contracts for finding and classifying recent Orq traces."""

from __future__ import annotations

from .compiler import CompiledPlan, CompileError, classification_legend, compile_query
from .export import (
    ExportCounts,
    ExportFilters,
    ExportNumericFilters,
    ExportSelection,
    ExportTask,
    ExportThresholdSelection,
    ExportTimes,
    ExportTrace,
    ExportValuesSelection,
    RunExport,
    build_export,
    export_json,
)
from .facets import load_facet_catalogue
from .filter_selector import NO_FILTER_LABEL, FilterSelectionError, select_filters
from .jev import build_datapoint, build_jev_evaluator, matches_selection, parse_datapoint_result, run_jev
from .models import (
    FACET_NAMES,
    CompiledQuery,
    FacetCatalogue,
    FacetName,
    FacetSelection,
    JevProjection,
    LegendItem,
    NumericFilters,
    PopulationRequest,
    RunRequest,
    RunSnapshot,
    RunState,
    SelectionRule,
    Snapshot,
    ThresholdSelection,
    TraceClassification,
    TraceDetail,
    TraceRecord,
    ValueSelection,
    validate_compiled_query,
)
from .orq_source import OrqTraceSource, build_oql
from .pipeline import build_run_store
from .projection import MAX_TOKEN_BUDGET, OMISSION_MARKER, estimate_tokens, project_trace, serialize_projection
from .run_store import RunStore
from .settings import (
    SETTINGS_PATH_ENV,
    DashboardSettings,
    effective_settings,
    load_settings,
    save_settings,
    settings_path,
)

__all__ = [
    'FACET_NAMES',
    'MAX_TOKEN_BUDGET',
    'NO_FILTER_LABEL',
    'OMISSION_MARKER',
    'SETTINGS_PATH_ENV',
    'CompileError',
    'CompiledPlan',
    'CompiledQuery',
    'DashboardSettings',
    'ExportCounts',
    'ExportFilters',
    'ExportNumericFilters',
    'ExportSelection',
    'ExportTask',
    'ExportThresholdSelection',
    'ExportTimes',
    'ExportTrace',
    'ExportValuesSelection',
    'FacetCatalogue',
    'FacetName',
    'FacetSelection',
    'FilterSelectionError',
    'JevProjection',
    'LegendItem',
    'NumericFilters',
    'OrqTraceSource',
    'PopulationRequest',
    'RunExport',
    'RunRequest',
    'RunSnapshot',
    'RunState',
    'RunStore',
    'SelectionRule',
    'Snapshot',
    'ThresholdSelection',
    'TraceClassification',
    'TraceDetail',
    'TraceRecord',
    'ValueSelection',
    'build_datapoint',
    'build_export',
    'build_jev_evaluator',
    'build_oql',
    'build_run_store',
    'classification_legend',
    'compile_query',
    'effective_settings',
    'estimate_tokens',
    'export_json',
    'load_facet_catalogue',
    'load_settings',
    'matches_selection',
    'parse_datapoint_result',
    'project_trace',
    'run_jev',
    'save_settings',
    'select_filters',
    'serialize_projection',
    'settings_path',
    'validate_compiled_query',
]
