"""Core contracts for finding and classifying recent Orq traces."""

from __future__ import annotations

from .jev import build_datapoint, build_jev_evaluator, matches_selection, parse_datapoint_result, run_jev
from .models import (
    FACET_NAMES,
    CompiledQuery,
    FacetCatalogue,
    FacetName,
    FacetOption,
    FacetSelection,
    JevProjection,
    LegendItem,
    NumericFilters,
    PopulationRequest,
    RunRequest,
    RunSnapshot,
    RunState,
    SelectionRule,
    Snapshot,
    ThresholdSelection,
    TraceClassification,
    TraceDetail,
    TraceRecord,
    ValueSelection,
    validate_compiled_query,
)
from .projection import MAX_TOKEN_BUDGET, OMISSION_MARKER, estimate_tokens, project_trace, serialize_projection

__all__ = [
    'FACET_NAMES',
    'MAX_TOKEN_BUDGET',
    'OMISSION_MARKER',
    'CompiledQuery',
    'FacetCatalogue',
    'FacetName',
    'FacetOption',
    'FacetSelection',
    'JevProjection',
    'LegendItem',
    'NumericFilters',
    'PopulationRequest',
    'RunRequest',
    'RunSnapshot',
    'RunState',
    'SelectionRule',
    'Snapshot',
    'ThresholdSelection',
    'TraceClassification',
    'TraceDetail',
    'TraceRecord',
    'ValueSelection',
    'build_datapoint',
    'build_jev_evaluator',
    'estimate_tokens',
    'matches_selection',
    'parse_datapoint_result',
    'project_trace',
    'run_jev',
    'serialize_projection',
    'validate_compiled_query',
]
